#See: https://cert-manager.io/docs/configuration/selfsigned/
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: ca-issuer
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: httpbin-local-cert
  namespace: certs
spec:
  secretName: httpbin-local-tls
  issuerRef:
    kind: ClusterIssuer
    name: ca-issuer
  dnsNames:
    - httpbin.local