---
apiVersion: v1
kind: Pod
metadata:
  name: toolbox
  namespace: default
spec:
  restartPolicy: Never
  containers:
    - name: alpine
      image: docker.io/library/alpine:latest
      imagePullPolicy: IfNotPresent
      args:
        - |-
          apk add --no-cache busybox-extras bind-tools bash curl wget httpie elinks jq openssl openssh-client strace procps nmap nmap-scripts nmap-ncat tcpdump
          sleep infinity vi
      command:
        - /bin/sh
        - -c
