kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    # See: https://github.com/kubernetes-sigs/kind/issues/3389#issuecomment-1784159342
    extraMounts:
      - hostPath: /dev
        containerPath: /dev
  - role: worker
    # See: https://github.com/kubernetes-sigs/kind/issues/3389#issuecomment-1784159342
    extraMounts:
      - hostPath: /dev
        containerPath: /dev
    extraPortMappings:
      - containerPort: 80
        hostPort: 80
        listenAddress: "0.0.0.0"
      - containerPort: 443
        hostPort: 443
        listenAddress: "0.0.0.0"
      - containerPort: 80
        hostPort: 8888
        listenAddress: "0.0.0.0"
      - containerPort: 80
        hostPort: 8889
        listenAddress: "0.0.0.0"